[package]
name = "neko-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "neko_core"
crate-type = ["staticlib"]

[dependencies]
crop = "0.4.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
